"""add task status and scheduled date

Revision ID: 747ae18f30ca
Revises: 
Create Date: 2026-08-12 21:38:08.602580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747ae18f30ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_steps') as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BACKLOG', name='taskstatus'), nullable=False, server_default='TODO'))
        batch_op.add_column(sa.Column('scheduled_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_steps') as batch_op:
        batch_op.drop_column('scheduled_date')
        batch_op.drop_column('status')
    # ### end Alembic commands ###
